# Generated by Django 3.2 on 2021-06-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('labels', '0002_alter_label_name'),
        ('statuses', '0002_alter_status_name'),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='label',
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(
                blank=True,
                through='tasks.LabelToTask',
                to='labels.Label',
                verbose_name='Метки',
            ),
        ),
        migrations.AlterField(
            model_name='labeltotask',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='tasks.task',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(
                blank=True,
                max_length=500,
                verbose_name='Описание',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='task_executor',
                to='users.taskuser',
                verbose_name='Исполнитель',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='statuses.status',
                verbose_name='Статус',
            ),
        ),
    ]
